scoreboard:
  title: "§a§lDEADPVP"
  lines:
    - "Liste des variables possibles"
    - "{player} -> nom du joueur"
    - "{server.playercount} -> (server peut être 'all')"
    - "{rank}"
    - "{rankcolor}"
menu:
  lines: 5
  title: "§6§lMenu"
  fill_inventory: AIR
  content:
    10:
      type: GRASS_BLOCK
      name: "§d§lCREATIF"
      lore:
        - "§bDescription:"
        - "§7  Construisez seul ou entre"
        - "§7  amis le plot de vos rêves!"
        - "§f"
        - "§9>>> {creatif.playercount} joueurs en créatif !"
      isEnchanted: false
      actions:
        sendTo: "creatif"
        sendMessage: "Bonjour"
        teleportTo:
          x: 0.0
          y: 150.0
          z: 0.0
          pitch: 0
          yaw: 0
        execute: "say Hello !"
    15:
      type: STONE
      name: "§d§lTRUC"
      lore:
        - "§bDescription:"
        - "§7  Construisez seul ou entre"
        - "§7  amis le plot de vos rêves!"
        - "§f"
        - "§9>>> {creatif.playercount} joueurs en créatif !"
      isEnchanted: false
      actions:
        sendMessage: "www.deadpvp.net"